2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_setup.py:_flush():76] Configure stats pid to 3146628
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_setup.py:_flush():76] Loading settings from /home/vs3041/.config/wandb/settings
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_setup.py:_flush():76] Loading settings from /scratch/gpfs/vs3041/cruijff/llama-recipes-fertility/recipes/quickstart/wandb/settings
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'recipes/quickstart/finetuning/finetuning.py', 'program_abspath': '/scratch/gpfs/vs3041/cruijff/llama-recipes-fertility/recipes/quickstart/finetuning/finetuning.py', 'program': '/scratch/gpfs/vs3041/cruijff/llama-recipes-fertility/recipes/quickstart/finetuning/finetuning.py'}
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_init.py:_log_setup():529] Logging user logs to /scratch/gpfs/vs3041/cruijff/llama-recipes-fertility/recipes/quickstart/wandb/run-20240809_045817-synfj0by/logs/debug.log
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_init.py:_log_setup():530] Logging internal logs to /scratch/gpfs/vs3041/cruijff/llama-recipes-fertility/recipes/quickstart/wandb/run-20240809_045817-synfj0by/logs/debug-internal.log
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_init.py:init():569] calling init triggers
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_init.py:init():619] starting backend
2024-08-09 04:58:17,468 INFO    MainThread:3146628 [wandb_init.py:init():623] setting up manager
2024-08-09 04:58:17,469 INFO    MainThread:3146628 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-08-09 04:58:17,472 INFO    MainThread:3146628 [wandb_init.py:init():631] backend started and connected
2024-08-09 04:58:17,473 INFO    MainThread:3146628 [wandb_init.py:init():720] updated telemetry
2024-08-09 04:58:17,480 INFO    MainThread:3146628 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-08-09 04:59:47,490 ERROR   MainThread:3146628 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-09 04:59:47,490 ERROR   MainThread:3146628 [wandb_init.py:init():1191] error in wandb.init()
Traceback (most recent call last):
  File "/home/vs3041/.cruijff/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/vs3041/.cruijff/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-08-09 04:59:48,515 WARNING MsgRouterThr:3146628 [router.py:message_loop():77] message_loop has been closed
